#! /usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

(new \Dotenv\Dotenv(__DIR__, '.env'))->load();

require __DIR__ . '/common/config/define.php';
require __DIR__ . '/common/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = require __DIR__ . '/console/config/main.php';

$application = new yii\console\Application($config);
$exitCode    = $application->run();

exit($exitCode);
